// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	protos/api.proto

It has these top-level messages:
	Void
	MinerRequest
	MinerInfo
	PoolStatsInfo
	BlockInfo
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MinerRequest struct {
	ID uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *MinerRequest) Reset()                    { *m = MinerRequest{} }
func (m *MinerRequest) String() string            { return proto.CompactTextString(m) }
func (*MinerRequest) ProtoMessage()               {}
func (*MinerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MinerRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type MinerInfo struct {
	Address               string  `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Name                  string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Pending               int64   `protobuf:"varint,3,opt,name=pending" json:"pending,omitempty"`
	HistoricalShare       float64 `protobuf:"fixed64,4,opt,name=historicalShare" json:"historicalShare,omitempty"`
	EffectiveCapacity     float64 `protobuf:"fixed64,5,opt,name=effectiveCapacity" json:"effectiveCapacity,omitempty"`
	Deadline              uint64  `protobuf:"varint,6,opt,name=deadline" json:"deadline,omitempty"`
	LastActiveBlockHeight uint64  `protobuf:"varint,7,opt,name=lastActiveBlockHeight" json:"lastActiveBlockHeight,omitempty"`
	NConf                 int32   `protobuf:"varint,8,opt,name=nConf" json:"nConf,omitempty"`
	PayoutDetail          string  `protobuf:"bytes,9,opt,name=payoutDetail" json:"payoutDetail,omitempty"`
}

func (m *MinerInfo) Reset()                    { *m = MinerInfo{} }
func (m *MinerInfo) String() string            { return proto.CompactTextString(m) }
func (*MinerInfo) ProtoMessage()               {}
func (*MinerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MinerInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MinerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MinerInfo) GetPending() int64 {
	if m != nil {
		return m.Pending
	}
	return 0
}

func (m *MinerInfo) GetHistoricalShare() float64 {
	if m != nil {
		return m.HistoricalShare
	}
	return 0
}

func (m *MinerInfo) GetEffectiveCapacity() float64 {
	if m != nil {
		return m.EffectiveCapacity
	}
	return 0
}

func (m *MinerInfo) GetDeadline() uint64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *MinerInfo) GetLastActiveBlockHeight() uint64 {
	if m != nil {
		return m.LastActiveBlockHeight
	}
	return 0
}

func (m *MinerInfo) GetNConf() int32 {
	if m != nil {
		return m.NConf
	}
	return 0
}

func (m *MinerInfo) GetPayoutDetail() string {
	if m != nil {
		return m.PayoutDetail
	}
	return ""
}

type PoolStatsInfo struct {
	MinerCount            int32   `protobuf:"varint,1,opt,name=minerCount" json:"minerCount,omitempty"`
	EffectivePoolCapacity float64 `protobuf:"fixed64,2,opt,name=effectivePoolCapacity" json:"effectivePoolCapacity,omitempty"`
	NetDiff               float64 `protobuf:"fixed64,3,opt,name=netDiff" json:"netDiff,omitempty"`
}

func (m *PoolStatsInfo) Reset()                    { *m = PoolStatsInfo{} }
func (m *PoolStatsInfo) String() string            { return proto.CompactTextString(m) }
func (*PoolStatsInfo) ProtoMessage()               {}
func (*PoolStatsInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PoolStatsInfo) GetMinerCount() int32 {
	if m != nil {
		return m.MinerCount
	}
	return 0
}

func (m *PoolStatsInfo) GetEffectivePoolCapacity() float64 {
	if m != nil {
		return m.EffectivePoolCapacity
	}
	return 0
}

func (m *PoolStatsInfo) GetNetDiff() float64 {
	if m != nil {
		return m.NetDiff
	}
	return 0
}

type BlockInfo struct {
	Height              uint64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	BaseTarget          uint64 `protobuf:"varint,2,opt,name=baseTarget" json:"baseTarget,omitempty"`
	Scoop               uint32 `protobuf:"varint,3,opt,name=scoop" json:"scoop,omitempty"`
	GenerationSignature string `protobuf:"bytes,4,opt,name=generationSignature" json:"generationSignature,omitempty"`
	MinerID             uint64 `protobuf:"varint,5,opt,name=minerID" json:"minerID,string,omitempty"`
	Miner               string `protobuf:"bytes,6,opt,name=miner" json:"miner,omitempty"`
	Deadline            uint64 `protobuf:"varint,7,opt,name=deadline" json:"deadline,omitempty"`
	Created             string `protobuf:"bytes,8,opt,name=created" json:"created,omitempty"`
}

func (m *BlockInfo) Reset()                    { *m = BlockInfo{} }
func (m *BlockInfo) String() string            { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()               {}
func (*BlockInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BlockInfo) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockInfo) GetBaseTarget() uint64 {
	if m != nil {
		return m.BaseTarget
	}
	return 0
}

func (m *BlockInfo) GetScoop() uint32 {
	if m != nil {
		return m.Scoop
	}
	return 0
}

func (m *BlockInfo) GetGenerationSignature() string {
	if m != nil {
		return m.GenerationSignature
	}
	return ""
}

func (m *BlockInfo) GetMinerID() uint64 {
	if m != nil {
		return m.MinerID
	}
	return 0
}

func (m *BlockInfo) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *BlockInfo) GetDeadline() uint64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *BlockInfo) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func init() {
	proto.RegisterType((*Void)(nil), "api.Void")
	proto.RegisterType((*MinerRequest)(nil), "api.MinerRequest")
	proto.RegisterType((*MinerInfo)(nil), "api.MinerInfo")
	proto.RegisterType((*PoolStatsInfo)(nil), "api.PoolStatsInfo")
	proto.RegisterType((*BlockInfo)(nil), "api.BlockInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Api service

type ApiClient interface {
	GetMinerInfo(ctx context.Context, in *MinerRequest, opts ...grpc.CallOption) (*MinerInfo, error)
	GetPoolStatsInfo(ctx context.Context, in *Void, opts ...grpc.CallOption) (*PoolStatsInfo, error)
	GetBlockInfo(ctx context.Context, in *Void, opts ...grpc.CallOption) (*BlockInfo, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GetMinerInfo(ctx context.Context, in *MinerRequest, opts ...grpc.CallOption) (*MinerInfo, error) {
	out := new(MinerInfo)
	err := grpc.Invoke(ctx, "/api.Api/GetMinerInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetPoolStatsInfo(ctx context.Context, in *Void, opts ...grpc.CallOption) (*PoolStatsInfo, error) {
	out := new(PoolStatsInfo)
	err := grpc.Invoke(ctx, "/api.Api/GetPoolStatsInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetBlockInfo(ctx context.Context, in *Void, opts ...grpc.CallOption) (*BlockInfo, error) {
	out := new(BlockInfo)
	err := grpc.Invoke(ctx, "/api.Api/GetBlockInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiServer interface {
	GetMinerInfo(context.Context, *MinerRequest) (*MinerInfo, error)
	GetPoolStatsInfo(context.Context, *Void) (*PoolStatsInfo, error)
	GetBlockInfo(context.Context, *Void) (*BlockInfo, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_GetMinerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetMinerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetMinerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetMinerInfo(ctx, req.(*MinerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetPoolStatsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetPoolStatsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetPoolStatsInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetPoolStatsInfo(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetBlockInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetBlockInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetBlockInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetBlockInfo(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMinerInfo",
			Handler:    _Api_GetMinerInfo_Handler,
		},
		{
			MethodName: "GetPoolStatsInfo",
			Handler:    _Api_GetPoolStatsInfo_Handler,
		},
		{
			MethodName: "GetBlockInfo",
			Handler:    _Api_GetBlockInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/api.proto",
}

func init() { proto.RegisterFile("protos/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x13, 0x27, 0xa9, 0x47, 0x69, 0x69, 0x97, 0x8b, 0x56, 0x79, 0xa8, 0x22, 0x3f, 0x45,
	0x02, 0x15, 0x44, 0xf8, 0x81, 0x12, 0x4b, 0x25, 0x0f, 0x48, 0x68, 0x83, 0x78, 0xdf, 0xda, 0x63,
	0x67, 0x85, 0xbb, 0x6b, 0xec, 0x09, 0x52, 0x9f, 0xf8, 0x11, 0xfe, 0x83, 0xef, 0xe2, 0x0f, 0xd0,
	0x8e, 0xeb, 0x5c, 0x4a, 0xde, 0xe6, 0xcc, 0x9c, 0xf5, 0xec, 0x39, 0x67, 0x0d, 0x17, 0x55, 0xed,
	0xc8, 0x35, 0x6f, 0x75, 0x65, 0xae, 0xb9, 0x14, 0x7d, 0x5d, 0x99, 0x78, 0x08, 0xe1, 0x37, 0x67,
	0xb2, 0xf8, 0x0a, 0xc6, 0x9f, 0x8d, 0xc5, 0x5a, 0xe1, 0x8f, 0x0d, 0x36, 0x24, 0xce, 0xa1, 0xb7,
	0x4c, 0x64, 0x30, 0x0d, 0x66, 0xa1, 0xea, 0x2d, 0x93, 0xf8, 0x4f, 0x0f, 0x22, 0x26, 0x2c, 0x6d,
	0xee, 0x84, 0x84, 0x91, 0xce, 0xb2, 0x1a, 0x9b, 0x86, 0x29, 0x91, 0xea, 0xa0, 0x10, 0x10, 0x5a,
	0x7d, 0x8f, 0xb2, 0xc7, 0x6d, 0xae, 0x3d, 0xbb, 0x42, 0x9b, 0x19, 0x5b, 0xc8, 0xfe, 0x34, 0x98,
	0xf5, 0x55, 0x07, 0xc5, 0x0c, 0x9e, 0xad, 0x4d, 0x43, 0xae, 0x36, 0xa9, 0x2e, 0x57, 0x6b, 0x5d,
	0xa3, 0x0c, 0xa7, 0xc1, 0x2c, 0x50, 0x4f, 0xdb, 0xe2, 0x0d, 0x5c, 0x62, 0x9e, 0x63, 0x4a, 0xe6,
	0x27, 0x2e, 0x74, 0xa5, 0x53, 0x43, 0x0f, 0x72, 0xc0, 0xdc, 0xff, 0x07, 0x62, 0x02, 0xa7, 0x19,
	0xea, 0xac, 0x34, 0x16, 0xe5, 0x90, 0x35, 0x6c, 0xb1, 0xf8, 0x00, 0x2f, 0x4b, 0xdd, 0xd0, 0x0d,
	0x9f, 0xf8, 0x58, 0xba, 0xf4, 0xfb, 0x27, 0x34, 0xc5, 0x9a, 0xe4, 0x88, 0x89, 0xc7, 0x87, 0xe2,
	0x05, 0x0c, 0xec, 0xc2, 0xd9, 0x5c, 0x9e, 0x4e, 0x83, 0xd9, 0x40, 0xb5, 0x40, 0xc4, 0x30, 0xae,
	0xf4, 0x83, 0xdb, 0x50, 0x82, 0xa4, 0x4d, 0x29, 0x23, 0x56, 0x7d, 0xd0, 0x8b, 0x7f, 0xc1, 0xd9,
	0x17, 0xe7, 0xca, 0x15, 0x69, 0x6a, 0xd8, 0xbc, 0x2b, 0x80, 0x7b, 0xef, 0xe4, 0xc2, 0x6d, 0x2c,
	0xb1, 0x7f, 0x03, 0xb5, 0xd7, 0xf1, 0x17, 0xdc, 0x2a, 0xf2, 0x27, 0xb7, 0x72, 0x7b, 0x2c, 0xf7,
	0xf8, 0xd0, 0x9b, 0x6c, 0x91, 0x12, 0x93, 0xe7, 0x6c, 0x72, 0xa0, 0x3a, 0x18, 0xff, 0x0d, 0x20,
	0x62, 0x29, 0xbc, 0xfd, 0x15, 0x0c, 0xd7, 0xad, 0xde, 0x36, 0xdc, 0x47, 0xe4, 0x6f, 0x75, 0xa7,
	0x1b, 0xfc, 0xaa, 0xeb, 0x02, 0x89, 0x57, 0x85, 0x6a, 0xaf, 0xe3, 0x0d, 0x68, 0x52, 0xe7, 0x2a,
	0xfe, 0xfa, 0x99, 0x6a, 0x81, 0x78, 0x07, 0xcf, 0x0b, 0xb4, 0x58, 0x6b, 0x32, 0xce, 0xae, 0x4c,
	0x61, 0x35, 0x6d, 0x1e, 0x43, 0x8c, 0xd4, 0xb1, 0x91, 0xbf, 0x27, 0x6b, 0x5d, 0x26, 0x1c, 0x5f,
	0xa8, 0x3a, 0xe8, 0x37, 0x70, 0xc9, 0x89, 0x45, 0xaa, 0x05, 0x07, 0x51, 0x8e, 0x9e, 0x44, 0x29,
	0x61, 0x94, 0xd6, 0xa8, 0x09, 0x33, 0x8e, 0x25, 0x52, 0x1d, 0x7c, 0xff, 0x3b, 0x80, 0xfe, 0x4d,
	0x65, 0xc4, 0x1c, 0xc6, 0xb7, 0x48, 0xbb, 0x87, 0x7b, 0x79, 0xed, 0xdf, 0xff, 0xfe, 0x4b, 0x9f,
	0x9c, 0xef, 0x5a, 0x9e, 0x12, 0x9f, 0x88, 0x39, 0x5c, 0xdc, 0x22, 0x1d, 0x86, 0x16, 0x31, 0xcb,
	0xff, 0x2a, 0x13, 0xc1, 0xe5, 0xc1, 0x38, 0x3e, 0x11, 0xaf, 0x79, 0xd3, 0xce, 0xe7, 0xbd, 0x03,
	0xed, 0x86, 0xed, 0x28, 0x3e, 0xb9, 0x1b, 0xf2, 0x1f, 0x38, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff,
	0x42, 0x77, 0x89, 0x96, 0x95, 0x03, 0x00, 0x00,
}
