// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import time "time"
import "github.com/PoC-Consortium/Nogrod/pkg/wallet"

// WalletHandler is an autogenerated mock type for the WalletHandler type
type WalletHandler struct {
	mock.Mock
}

// CalcOptimalTxFee provides a mock function with given fields: _a0
func (_m *WalletHandler) CalcOptimalTxFee(_a0 uint64) (int64, error) {
	ret := _m.Called(_a0)

	var r0 int64
	if rf, ok := ret.Get(0).(func(uint64) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountInfo provides a mock function with given fields: _a0
func (_m *WalletHandler) GetAccountInfo(_a0 uint64) (*wallet.GetAccountReply, error) {
	ret := _m.Called(_a0)

	var r0 *wallet.GetAccountReply
	if rf, ok := ret.Get(0).(func(uint64) *wallet.GetAccountReply); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.GetAccountReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockInfo provides a mock function with given fields: _a0
func (_m *WalletHandler) GetBlockInfo(_a0 uint64) (*wallet.GetBlockReply, error) {
	ret := _m.Called(_a0)

	var r0 *wallet.GetBlockReply
	if rf, ok := ret.Get(0).(func(uint64) *wallet.GetBlockReply); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.GetBlockReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGenerationTime provides a mock function with given fields: height
func (_m *WalletHandler) GetGenerationTime(height uint64) (int32, error) {
	ret := _m.Called(height)

	var r0 int32
	if rf, ok := ret.Get(0).(func(uint64) int32); ok {
		r0 = rf(height)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(height)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIncomingMsgsSince provides a mock function with given fields: date
func (_m *WalletHandler) GetIncomingMsgsSince(date time.Time) (map[uint64]string, error) {
	ret := _m.Called(date)

	var r0 map[uint64]string
	if rf, ok := ret.Get(0).(func(time.Time) map[uint64]string); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMiningInfo provides a mock function with given fields:
func (_m *WalletHandler) GetMiningInfo() (*wallet.GetMiningInfoReply, error) {
	ret := _m.Called()

	var r0 *wallet.GetMiningInfoReply
	if rf, ok := ret.Get(0).(func() *wallet.GetMiningInfoReply); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.GetMiningInfoReply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRewardRecipients provides a mock function with given fields:
func (_m *WalletHandler) GetRewardRecipients() (map[uint64]bool, error) {
	ret := _m.Called()

	var r0 map[uint64]bool
	if rf, ok := ret.Get(0).(func() map[uint64]bool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]bool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransaction provides a mock function with given fields: _a0
func (_m *WalletHandler) GetTransaction(_a0 uint64) (*wallet.GetTransactionReply, bool, error) {
	ret := _m.Called(_a0)

	var r0 *wallet.GetTransactionReply
	if rf, ok := ret.Get(0).(func(uint64) *wallet.GetTransactionReply); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wallet.GetTransactionReply)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(uint64) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SendPayment provides a mock function with given fields: _a0, _a1
func (_m *WalletHandler) SendPayment(_a0 uint64, _a1 int64) (uint64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 uint64
	if rf, ok := ret.Get(0).(func(uint64, int64) uint64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendPayments provides a mock function with given fields: _a0
func (_m *WalletHandler) SendPayments(_a0 map[uint64]int64) (uint64, error) {
	ret := _m.Called(_a0)

	var r0 uint64
	if rf, ok := ret.Get(0).(func(map[uint64]int64) uint64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[uint64]int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitNonce provides a mock function with given fields: _a0, _a1, _a2
func (_m *WalletHandler) SubmitNonce(_a0 uint64, _a1 uint64, _a2 uint64) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, uint64, uint64) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WonBlock provides a mock function with given fields: _a0, _a1, _a2
func (_m *WalletHandler) WonBlock(_a0 uint64, _a1 uint64, _a2 uint64) (bool, *wallet.GetBlockReply, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 bool
	if rf, ok := ret.Get(0).(func(uint64, uint64, uint64) bool); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 *wallet.GetBlockReply
	if rf, ok := ret.Get(1).(func(uint64, uint64, uint64) *wallet.GetBlockReply); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*wallet.GetBlockReply)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(uint64, uint64, uint64) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
